#!/bin/bash

speed=15
size=1500x500+210+0

main() {
  if [ -z $(xdo id -n dropterm) ]; then
    wm=$(xprop -id $(xprop -root -notype _NET_SUPPORTING_WM_CHECK | awk '{print $NF}') -notype -f _NET_WM_NAME 8t | awk '/NAME/{ gsub(/"/,""); print $NF }')
    if [[ "$wm" == "bspwm" ]] ; then
      bspc rule -a URxvt:dropterm sticky=on state=floating rectangle=$size
    fi
    urxvtc -name dropterm -e zsh -c "tmux new-session -A -s dropterm";
  else
    wininfo
    if (($y < 0)) ; then
      move +$speed 
      xdo activate -n dropterm
    else
      move -$speed
    fi
  fi
}

move() {
  for ((i=0; i<=$height; i+=$speed)) ; do
    xdo move -y $1 -n dropterm
  done
}

wininfo() {
  id=$(xdo id -n dropterm)
  while read -a line ; do
    case ${line[*]} in
      Height:*) height=${line[1]} ;;
      Relative\ upper-left\ Y:*) 
        y=${line[3]} ;;
    esac
  done < <(xwininfo -id $id)
}

main
